const HOME_RENTAL_PATH = '/home/rental';
const ERROR_403_PATH = '/error/403';
const SIGN_IN_PATH = '/auth/signin';
const ADMIN_ROOM_PATH = '/room/admin';
const ALL_MANAGERS_PATH = '/manager';
const ALL_USERS_PATH = '/user';
const CREATE_MANAGER_PATH = '/manager/create';

export default {
    HOME_RENTAL_PATH: HOME_RENTAL_PATH,
    ERROR_403_PATH : ERROR_403_PATH,
    SIGN_IN_PATH: SIGN_IN_PATH,
    ADMIN_ROOM_PATH: ADMIN_ROOM_PATH,
    ALL_MANAGERS_PATH: ALL_MANAGERS_PATH,
    ALL_USERS_PATH: ALL_USERS_PATH,
    CREATE_MANAGER_PATH: CREATE_MANAGER_PATH
}